# Generated by Django 5.2.8 on 2025-12-03 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_receta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receta',
            name='ingredientes',
            field=models.ManyToManyField(related_name='recetas', to='app.ingrediente'),
        ),
        migrations.CreateModel(
            name='IngredienteRecetas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.FloatField()),
                ('unidad', models.CharField(choices=[('G', 'Gramos'), ('KG', 'Kilogramos'), ('L', 'Litro'), ('U', 'Unidades')], max_length=2)),
                ('ingrediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.ingrediente')),
                ('receta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.receta')),
            ],
        ),
    ]
