# Generated by Django 5.2.8 on 2025-12-03 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_receta_ingredientes_ingredienterecetas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receta',
            name='ingredientes',
            field=models.ManyToManyField(related_name='recetas', through='app.IngredienteRecetas', to='app.ingrediente'),
        ),
    ]
